### ISSUE TITLE
Compiler crash on method call in the emit stage

### ISSUE THREAD

**Issue by ark3** [datawire/quark#12]
This code crashes the compiler in the emit stage:
```
class Foo {
    void next() {
    }

    void test() {
        next();
    }
}
```
**Workaround**: call `self.next()` instead of `next()`.

```
$ quark --java=java attrerror.q 
Traceback (most recent call last):
  File "/Users/ark3/.virtualenvs/datawire/bin/quark", line 9, in <module>
    load_entry_point('datawire-quark==0.1.0', 'console_scripts', 'quark')()
  File "/Users/ark3/Dropbox/datawire/quark/quark/compiler.py", line 528, in main
    exit(_main(docopt(main.__doc__)))
  File "/Users/ark3/Dropbox/datawire/quark/quark/compiler.py", line 504, in _main
    c.compile()
  File "/Users/ark3/Dropbox/datawire/quark/quark/compiler.py", line 477, in compile
    self.emit(backend)
  File "/Users/ark3/Dropbox/datawire/quark/quark/compiler.py", line 481, in emit
    self.root.traverse(backend)
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 89, in traverse
    visit(self, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/java.py", line 57, in visit_Class
    self.files["%s.java" % c.name.text] = c.match(self.dfnr)
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 97, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/java.py", line 146, in match_Class
    body = "\n".join([d.match(self) for d in c.definitions])
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 97, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/java.py", line 166, in match_Function
    body = " %s" % m.body.match(self.stmtr) if m.body else ";"
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 97, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/java.py", line 259, in match_Block
    return "{%s}" % indent("\n".join([s.match(self) for s in b.statements]))
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 97, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/java.py", line 236, in match_ExprStmt
    return "%s;" % stmt.expr.match(self.exprr)
  File "/Users/ark3/Dropbox/datawire/quark/quark/ast.py", line 97, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/java.py", line 285, in match_Call
    return self.invoke(type, c.expr, [a.match(self) for a in c.args])
  File "/Users/ark3/Dropbox/datawire/quark/quark/dispatch.py", line 52, in __call__
    return method(self.object, *args, **kwargs)
  File "/Users/ark3/Dropbox/datawire/quark/quark/java.py", line 346, in invoke
    return "(%s).%s(%s)" % (expr.expr.match(self),
AttributeError: 'Var' object has no attribute 'expr'
```

**Comment by bozzzzo** [comment]
This now generates correct code
