### ISSUE TITLE
Quark -> Python: NameError: global name 'Runtime' is not defined

### ISSUE THREAD

**Issue by plombardi89** [datawire/quark#146]
Just received this error with a piece of Quark that looks like the following:

Error:
```python
>>> Datawire.getToken()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/plombardi/.local/lib/python2.7/site-packages/util/__init__.py", line 24, in getToken
    (Runtime).fail(u"Environment variable 'DATAWIRE_TOKEN' is not set.");
NameError: global name 'Runtime' is not defined
```

Quark:
```java
  class Datawire 
  {

    static String TOKEN_VARIABLE_NAME = "DATAWIRE_TOKEN";
  
    @doc("Returns the Datawire Access Token by reading the environment variable DATAWIRE_TOKEN.")
    static String getToken()
    {
        String token = EnvironmentVariable(TOKEN_VARIABLE_NAME).get();
        if (token == null)
        {
            Runtime.fail("Environment variable 'DATAWIRE_TOKEN' is not set.");
        }

        return token;
    }
  }
```

Ran `quark install --python <file containing the bug>.q`

Then:

```bash
$ python
>>> from util import Datawire
>>> Datawire.getToken()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/plombardi/.local/lib/python2.7/site-packages/util/__init__.py", line 24, in getToken
    (Runtime).fail(u"Environment variable 'DATAWIRE_TOKEN' is not set.");
NameError: global name 'Runtime' is not defined
```

**Comment by ark3** [comment]
To try to boil this down to something smaller:

```
void main(List<String> args) {
    Runtime.fail("failed");
}
```

On Python, Ruby, and JavaScript, the result is a NameError or equivalent. On Java, the javac stage errors out because `java.lang.Runtime` does not have a `fail(java.lang.String)` method.

In summary, it appears the problem is that `Runtime` is passed through by the Quark compiler as okay to use even though it is never defined. Is that what you're talking about in your report?

**Comment by bozzzzo** [comment]
But `Runtime` is an interface. Is the bug that quark allows calling methods on interfaces as if they are static?

**Comment by plombardi89** [comment]
I'm expecting Runtime.fail to throw some kind of error containing the specified message rather than tell me Runtime itself doesn't exist...

**Comment by bozzzzo** [comment]
It looks like you're hitting a quark compiler error that allows you to call interface methods as if they are static methods.

Change 
```diff
-             Runtime.fail("Environment variable 'DATAWIRE_TOKEN' is not set.");
+             concurrent.Context.runtime().fail("Environment variable 'DATAWIRE_TOKEN' is not set.");
```

**Comment by bozzzzo** [comment]
Bah, forgot to link this issue in 25dd062
