### ISSUE TITLE
Trying to compile a quark file without the files for referenced packages crashes the compiler

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#18]
We should catch this and throw a reasonable error like "package foo must also be compiled" or similar

Instead, currently we get the following crash:

```
Traceback (most recent call last):
  File "/Users/janicekarin/virtualenv/bin/quark", line 9, in <module>
    load_entry_point('datawire-quark==0.1.0', 'console_scripts', 'quark')()
  File "/Users/janicekarin/quark/quark/compiler.py", line 566, in main
    exit(_main(docopt(main.__doc__)))
  File "/Users/janicekarin/quark/quark/compiler.py", line 542, in _main
    c.compile()
  File "/Users/janicekarin/quark/quark/compiler.py", line 497, in compile
    self.root.traverse(use)
  File "/Users/janicekarin/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/janicekarin/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/janicekarin/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/janicekarin/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/janicekarin/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/janicekarin/quark/quark/ast.py", line 93, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/Users/janicekarin/quark/quark/ast.py", line 94, in traverse
    leave(self, *args, **kwargs)
  File "/Users/janicekarin/quark/quark/compiler.py", line 233, in leave_Type
    if n.text in type.env:
AttributeError: 'NoneType' object has no attribute 'env'
```

**Comment by rhs** [comment]
Can you supply the input files and command line invocation that caused this?

**Comment by janicedatawire** [comment]
Try any of the following (from the base quark directory) using the calculatepi.q example checked in at quark/examples:

`quark --python ~/quark-examples/python examples/calculatepi.q`

`quark --java ~/quark-examples/java examples/calculatepi.q`

`quark --javascript ~/quark-examples/javascript examples/calculatepi.q`

**Comment by bozzzzo** [comment]
Not enough info to reproduce
