### ISSUE TITLE
Quark Compiler Exception (no matching method)

### ISSUE THREAD

**Issue by plombardi89** [datawire/quark#64]
Traceback (most recent call last):
  File "/home/plombardi/workspace/virtenvs/datawire_nov/bin/quark", line 11, in <module>
    sys.exit(call_main())
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/command.py", line 155, in call_main
    exit(main(docopt(__doc__)))
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/command.py", line 122, in main
    res = compiler.main(filenames, **compiler_args)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/compiler.py", line 701, in main
    c.compile()
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/compiler.py", line 680, in compile
    self.emit(backend)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/compiler.py", line 684, in emit
    self.root.traverse(backend)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 100, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 100, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 100, in traverse
    c.traverse(visitor, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 96, in traverse
    visit(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 91, in visit_Class
    self.files["%s/%s.java" % (pkg.replace(".", "/"), c.name.text)] = c.match(self.dfnr)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 104, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 242, in match_Class
    body = "\n".join(self.class_body(c))
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 206, in class_body
    result.extend([d.match(self) for d in cls.definitions])
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 104, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 265, in match_Function
    body = " %s" % m.body.match(self.stmtr) if m.body else ";"
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 104, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 332, in match_Block
    return "{%s}" % indent("\n".join([s.match(self) for s in b.statements]))
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 104, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 297, in match_Local
    return "%s;" % stmt.declaration.match(self)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 104, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 303, in match_Declaration
    value = self.exprr.maybe_cast(d.type, d.value)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 356, in maybe_cast
    result = expr.match(self)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 104, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 399, in match_Call
    return self.invoke(type, c.expr, [self.coerce(a) for a in c.args])
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/dispatch.py", line 52, in __call__
    return method(self.object, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 471, in invoke
    return "new %s(%s)" % (expr.match(self), ", ".join(args))
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/ast.py", line 104, in match
    return self.lookup(transform, "match")(self, *args, **kwargs)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/java.py", line 416, in match_Attr
    return self.get(type, a.resolved.type, a.expr, a.attr)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/dispatch.py", line 51, in __call__
    method = self.get(types)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/dispatch.py", line 47, in get
    self.dispatcher.error(types)
  File "/home/plombardi/workspace/virtenvs/datawire_nov/lib/python2.7/site-packages/quark/dispatch.py", line 75, in error
    raise TypeError("no matching method: (%s)" % ", ".join([t.__name__ for t in types]))
TypeError: no matching method: (Package, Class, Var, Name)

Caused By:

```java
@version("0.0.1")
@doc("A high-level API for communicating with the Datawire Directory 2.0")
package boston {

  interface ServicePublisher {
    void register();
    void heartbeat();
  }

  class BasicServicePublisher extends ServicePublisher, Task, WSHandler {

    Runtime runtime;
    HostAndPort registryAddress;
    WebSocket socket;
    String serviceName;
    ServiceEndpoint endpoint;
    String clientId = "default";

    BasicServiceRegistry(Runtime runtime,
                         HostAndPort registryAddress,
                         String clientId,
                         String serviceName,
                         ServiceEndpoint endpoint) {

      self.runtime = runtime;
      self.registryAddress = registryAddress;
      self.runtime.open(registryAddress.toString(), self);
      self.runtime.schedule(self, 5.0);
      self.serviceName = serviceName;
      self.endpoint = endpoint;
    }

    void send(JSONObject json) {
      if (json == null) {
        // throw IllegalArgument()
      }

      if (self.socket != null) {
        socket.send(json.toString());
      } else {
        // throw ConnectionNotEstablished()
      }
    }

    void register() {
      message.ServiceRegistration registration = message.ServiceRegistration(clientId, serviceName, endpoint);
      send(registration.toJson());
    }

    void heartbeat() {
      JSONObject json = new JSONObject();
      json["message"] = "heartbeat";
      json["sender"]  = clientId;
      send(json);
    }

    void onWSConnected(WebSocket socket) {
      self.socket = socket;
      register();
    }

    void onExecute(Runtime runtime) {
      heartbeat();
      self.runtime.schedule(self, 5.0);
    }
  }

  @doc("A service record maps a named service to a set of known endpoints.")
  class ServiceRecord {

    String name;
    List<String> endpoints;

    ServiceRecord(String name) {
      self.name = name;
      self.endpoints = new List<String>();
    }

    String toString() {
      String result  = "";

      String header  = "Record: " + name;
      String pointer = " --> ";

      result = result + header;

      // build padding for pretty printing
      String padding = "";
      int pdx = 0;
      while(pdx < header.size()) {
        padding = padding + " ";
        pdx = pdx + 1;
      }

      // build the result
      int edx = 0;
      while(edx < endpoints.size()) {
        if (edx != 0) {
          result = result + padding;
        }

        result = result + pointer + endpoints[edx] + "\n";
        edx = edx + 1;
      }

      return result;
    }
  }

  class Watson extends WSHandler {
    Runtime runtime;
    WebSocket socket;


  }

  class Client extends WSHandler {

        Runtime runtime;
        HostAndPort directory;
        String clientId;
        WebSocket socket;
        bool connected;
        String test;

        Client(Runtime runtime, HostAndPort directory) {
          self.runtime = runtime;
          self.directory = directory;
        }

        void connect() {
            self.runtime.open(directory.toString(), self);
        }

        void registerService(String name, String address, int _port, bool secured) {
          NetworkAddress addr = new NetworkAddress(address, "ipv4");
          ServicePort port = new ServicePort("http", _port, secured);
          ServiceEndpoint endpoint = new ServiceEndpoint(addr, port);
          message.ServiceRegistration registration = new message.ServiceRegistration(clientId, name, endpoint);
          print(registration.toJson());
        }

        void ws_send(String message) {
          socket.send(message);
        }

        void onWSConnected(WebSocket socket) {
          self.socket = socket;
        }

        void onWSClose(WebSocket socket) {
          print("socket closed");
        }
    }

    class HostAndPort {
      String host;
      int port;

      HostAndPort(String host, int port) {
        self.host = host;
        self.port = port;
      }

      String toString() {
        return host + ":" + port.toString();
      }
    }

    class ServiceEndpoint {
      NetworkAddress address;
      ServicePort port;

      ServiceEndpoint(NetworkAddress address, ServicePort port) {
        self.address = address;
        self.port = port;
      }

      JSONObject toJson() {
        JSONObject json = new JSONObject();
        json["address"] = address.toJson();
        json["port"] = port.toJson();
        return json;
      }
    }

    class ServicePort {
      String name;
      int port;
      bool secure;

      ServicePort(String name, int port, bool secure) {
        self.name = name;
        self.port = port;
        self.secure = secure;
      }

      JSONObject toJson() {
        JSONObject json = new JSONObject();
        json["name"] = name;
        json["port"] = port;
        json["secure"] = new JSONObject().setBool(secure);
        return json;
      }
    }

    class NetworkAddress {
      String host;
      String protocol;

      NetworkAddress(String host, String protocolType) {
        self.host = host;
        self.protocol = protocolType;
      }

      JSONObject toJson() {
        JSONObject json = new JSONObject();
        json["host"] = host;
        json["protocol"] = protocol;
        return json;
      }
    }

    package message {
        class Message {
          @doc("Indicates the type of message being sent.")
          String type;

          @doc("Indicates the sender of the message.")
          String sender;

          Message(String type, String sender) {
            self.type = type;
            self.sender = sender;
          }

          JSONObject toJson();
        }

        class ServiceRegistration extends Message {

          String name;
          ServiceEndpoint endpoint;

          ServiceRegistration(String client, String name, ServiceEndpoint endpoint) {
            super("register", client);
            self.name = name;
            self.endpoint = endpoint;
          }

          JSONObject toJson() {
            JSONObject json = new JSONObject();
            json["type"] = self.type;
            json["sender"] = self.sender;
            json["name"] = name;
            json["endpoint"] = endpoint.toJson();
            return json;
          }
        }
    }
}
```

**Comment by plombardi89** [comment]
It's vomitting on this:

`message.ServiceRegistration registration = message.ServiceRegistration(clientId, serviceName, endpoint);`

in `BasicServicePublisher#register`

**Comment by bozzzzo** [comment]
This compiles with recent quark
