### ISSUE TITLE
User-defined macros evaluating to nothing in Javascript

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#69]
macros3.q defines a few macros used in testingMacros.q. They still work in Python and Java as is and the macro code is substituted for the macro call in the code. In Javascript the macro is removed but the evaluated code is not present in its place.

In Python:

```
def main():
    latitude = (38) + (53/60.0) + (55/3600.0);
    longitude = (-(77)) + (2/60.0) + (16/3600.0);
    _println((((repr(latitude)) + (u" degrees latitude and ")) + (repr(longitude))) + (u" degrees longitude."));
    _println((((repr(latitude)) + (u" degrees latitude and ")) + (repr(longitude))) + (u" degrees longitude."));
    _println((((repr(latitude)) + (u" degrees latitude and ")) + (repr(longitude))) + (u" degrees longitude."));
```

In Java:

```
public static void main() {
        Double latitude = (38) + (53/60.0) + (55/3600.0);
        Double longitude = (-(77)) + (2/60.0) + (16/3600.0);
        System.out.println((((Double.toString(latitude)) + (" degrees latitude and ")) + (Double.toString(longitude))) + (" degrees longitude."));
        System.out.println((((Double.toString(latitude)) + (" degrees latitude and ")) + (Double.toString(longitude))) + (" degrees longitude."));
        System.out.println((((Double.toString(latitude)) + (" degrees latitude and ")) + (Double.toString(longitude))) + (" degrees longitude."));
    }
```

In Javascript:

```
function main() {
    var latitude = ;
    var longitude = ;
    _qrt.print((((_qrt.toString(latitude)) + (" degrees latitude and ")) + (_qrt.toString(longitude))) + (" degrees longitude."));
    _qrt.print((((_qrt.toString(latitude)) + (" degrees latitude and ")) + (_qrt.toString(longitude))) + (" degrees longitude."));
    ;
}
```

Note: one of the print macros is evaluating; i have three print statements in the file using print() from the builtins and print2() and print3() from my macro file and the generated js code has two print statements so one was properly evaluated. However, the other one wasn't nor was the degrees macro.

Trying to run this in javascript then results in this error:

```
var latitude = ;
                   ^

SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

[macros3.txt](https://github.com/datawire/quark/files/47519/macros3.txt)
[testingMacros.txt](https://github.com/datawire/quark/files/47520/testingMacros.txt)

**Comment by bozzzzo** [comment]
Probably fixed.
